### ISSUE TITLE
docs add-cids-to-group: default CIDS won't upload

### ISSUE THREAD

**Issue by RafaelCaso** [PinataCloud/docs#40]
following the documentation as written the user is given the CIDs 
```
["QmVLwvmGehsrNEvhcCnnsw5RQNseohgEkFNN1848zNzdng", "bafkreih5aznjvttude6c3wbvqeebb6rlx5wkbzyppv7garjiubll2ceym4"]
```
which point to images of Pinata's logo. However, I was unable to upload to my groups using these CIDs. When I tried my own CIDs it worked fine.

Is this because my bearer token restricts group management?

If so, adding a note in the docs to clarify this might be beneficial

**Comment by stevedylandev** [comment]
Hey there! Yes that is correct, the docs is just showing an example of what a CID going into a group might look like. In reality you can only add files to groups that are pinned to your account. Thanks for the tip, we'll look at adjusting the docs to make that more clear :)
