### ISSUE TITLE
getting an error in ESM module.

### ISSUE THREAD

**Issue by Boby900** [PinataCloud/docs#44]
PFA for the refrence, I am trying to setup pinata using the express("ESM") so I can upload the assets to the pinata by calling the API endpoint.
```tsx
import { Response, Request, NextFunction } from "express";
import { db } from "../db/index.js";
import { contentTable } from "../db/schema.js";
import { randomUUID } from "crypto";
import { eq } from "drizzle-orm";
import { z, ZodError } from "zod";

import { PinataSDK } from "pinata";
import fs  from "fs";
import { Blob } from "buffer";

require("dotenv").config()

const pinata = new PinataSDK({
  pinataJwt: process.env.PINATA_JWT,
  pinataGateway: process.env.GATEWAY_URL
})
```

![Screenshot (707)](https://github.com/user-attachments/assets/bf7ca7c1-97e0-4138-8a9c-beb248118868)

**Comment by stevedylandev** [comment]
Hey there! If this repo is hosted could you send us the link here? I would like to see what's being passed into Blob. 

If you are using Express to build an API / Backend it does handle file uploads a bit differently. If that is the case let me know and I can put together an example repo (and likely add it to the docs as well)

**Comment by Boby900** [comment]
> Hey there! If this repo is hosted could you send us the link here? I would like to see what's being passed into Blob.
> 
> If you are using Express to build an API / Backend it does handle file uploads a bit differently. If that is the case let me know and I can put together an example repo (and likely add it to the docs as well)

thanks @stevedylandev  as always.
currently, that code is in my feature branch I have not pushed it to GitHub.
but I have just a text `hello world` in my `hello.txt` file and I am having this, don't know what's causing this error.
you can have a look at my project structure, PFA.
![Screenshot (708)](https://github.com/user-attachments/assets/26536e9e-5dd5-43d2-a68f-26cd967507da)
